### ISSUE TITLE
3DS AGB_FIRM info missing

### ISSUE THREAD

**Issue by trbocode** [mgba-emu/bios-dump#1]
According to 3dbrew, the 3DS arm7 contains a GBA bios.
The dump from my New 3DS, made using this tool, is identical to the DS ones.
I think it might be good to add that info.

**Comment by endrift** [comment]
N3DS (KTR) or N3DSXL (RED)? I can add the info.

**Comment by trbocode** [comment]
N3DSXL. 
Also, it's very likely that the other 3DS models have the same bios revision.

**Comment by endrift** [comment]
Added more info and speculative info in 9b2e4c4f3f43222b091b3da7efa8af2c434e2cf2.
