### ISSUE TITLE
My Compiling Issue

### ISSUE THREAD

**Issue by P0W3** [mgba-emu/bios-dump#4]
I was using the Command Prompt of Windows to compile bios-dump.c, but it did not successfully work.

Here is what I have.

![image](https://user-images.githubusercontent.com/18279115/103116457-95c6a780-4634-11eb-990f-a34e630abc11.png)

Here is what I did.

![image](https://user-images.githubusercontent.com/18279115/103116496-b0991c00-4634-11eb-8201-8c4bfbf37eb3.png)

Are there any requirements to compile a .c file to a .gba file?

**Comment by endrift** [comment]
You need to use devkitPro's tool 
chain. This is also not a support forum. I hope to provide a prebuilt version soon but if you don't have an actual bug this is the wrong place to post it.
